#! /bin/bash

set -e
set -u

dry_run=

eval $(grep 'version *=' setup.cfg | tr '[:upper:]' '[:lower:]' | sed 's/ *= */=/')
tag="v$version"
title="v$version"
$dry_run git tag "$tag" || printf 'WARNING: tag "%s" already exists\n' "$tag"
$dry_run git push --tags
blue=$(tput setaf 32)
sgr0=$(tput sgr0)

if which -s gh; then
    $dry_run gh release create --title "$title" --generate-notes "$tag"
else
    printf 'Next steps:\n'
    printf '1. Create new release on Github using tag=%s title=%s\n' "v$version" "v$version"
    printf '1.1 Use url %s\n' "https://github.com/dtmilano/viaduc/releases/new"
    OLDIFS="$IFS"
    IFS=$'\n' changelog=( $(git-log-from-last-tag) )
    IFS="$OLDIFS"
    for l in "${changelog[@]}"
    do
        printf '%s\n' "$l"
    done
    printf '2. Github Actions kicks off automatically to release new version\n'
fi

printf '😼 Now Github Actions should follow...\n'
